services:
  api:
    build:
      context: .
      dockerfile: ./docker/develop/Dockerfile
    container_name: api
    ports:
      - "8090:8080"
      - "2345:2345"
    command: sh -c "air"
    volumes:
      - ./:/app
    depends_on:
      - pdb
    environment:
      DEBUG_MODE: ${DEBUG_MODE:-false}
  pdb:
    image: postgres:17.5
    container_name: pdb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: root
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
    driver: local
